### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by michae1T** [apicollective/graphql-rest-proxy#1]
Does the code work?  Does the idea work?  Are there plans to continue?

**Comment by michae1T** [comment]
@benwaffle

**Comment by benwaffle** [comment]
@michae1T Yes, the code works. You can look at the included `config.json` for the format. The plan is to put it in production at Flow ASAP.

**Comment by michae1T** [comment]
@benwaffle 

I heard from @mbryzek  the idea was to spin this as a configurable companion to apibuilder - is that true?

As an experiment I overwrote config.json with an API we would like to use and cleared the overrides.  Was not able to get it to start up as apibuilder imports are not supported.

Basically, is this the extent of the project?  Do you know off hand any other big features that might be missing?  If there are plans to continue, how far off do you think this is it from supporting a fairly complex API set that pushes the limits in capability of many generators?  Also, what about supporting something advanced like stitching together multiple APIs?  I don't mean just imports but producing a unified schema with configuration but without writing code yourself.  Is this conceptually even possible?  If so how much effort are we talking about?

Thanks

**Comment by mbryzek** [comment]
@michae1T great to hear from you! Definitely plan is to fully support a complex API (flow's api has over 1000 operations at this point)

a unified schema across disparate companies is not something we have considered to date.

any interest in contributing?

**Comment by benwaffle** [comment]
@michae1T we cannot support apibuilder imports unless apibuilder is changed to pass it to the generators. The current approach for Flow is to use a custom script that downloads all the apis and imports in advance.
